# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ned < Formula
  desc "Open any remote file in your local editor over SSH or Docker"
  homepage "https://github.com/ValeryCherneykin/ned"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_amd64.tar.gz"
      sha256 "b510dd002a39cce251dfb2849611e3ec264b6fa8586ce29b9ceb2ec97d35697b"

      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_arm64.tar.gz"
      sha256 "4642a75f2d4e2ed5f43f00866ac3768a028c43851ffed86d4ffdedcccd0d7a8a"

      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_amd64.tar.gz"
      sha256 "465ea4eb620f7ebf5cb917326fd99227a7fcb39da473dabbd980a11e9026bee5"
      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_arm64.tar.gz"
      sha256 "693281aaddb3791163e1983fb9a4caee96f9762ba9c77e57de106a960adca26a"
      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  test do
    system "#{bin}/ned --version"
  end
end
