# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ned < Formula
  desc "Open any remote file in your local editor over SSH or Docker"
  homepage "https://github.com/ValeryCherneykin/ned"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_amd64.tar.gz"
      sha256 "fa86dea91f509515103dab1c38359a9f8b7426c5e33494f1a53debef46ff1c2a"

      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_arm64.tar.gz"
      sha256 "5ffc997fa024d06b9bd99b3eaa5ac43a22d2ec5d9d960a88621960f157b0fcd5"

      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_amd64.tar.gz"
      sha256 "ca0f6234486e9593b94d56750ec287272a0e741606bc7b75d089980361f7c5ea"
      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_arm64.tar.gz"
      sha256 "037205278e9207ce265af074acc0ff33d36c5ab36fed6ca1f80427c7db32c1e0"
      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  test do
    system "#{bin}/ned --version"
  end
end
