# typed: false
# frozen_string_literal: true
# This file was generated by GoReleaser. DO NOT EDIT.
class Ned < Formula
  desc "Open any remote file in your local editor over SSH or Docker"
  homepage "https://github.com/ValeryCherneykin/ned"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.2.0/ned_0.2.0_darwin_amd64.tar.gz"
      sha256 "f8dbca03316153053c71f43782dc32a62749ea176d624d4126257fa4c6516b90"

      def install
        bin.install "ned"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.2.0/ned_0.2.0_darwin_arm64.tar.gz"
      sha256 "e891c3547d867d5ddb8c98d8714596b9ce1877335044f66c3585249664069e19"

      def install
        bin.install "ned"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.2.0/ned_0.2.0_linux_amd64.tar.gz"
      sha256 "20a15dbc928a79b29393fdff4b69860ca7ec9517a2baf5e6d42cb656c30d9d7f"

      def install
        bin.install "ned"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.2.0/ned_0.2.0_linux_arm64.tar.gz"
      sha256 "721f4794f20e0f22768fb01abdabdd24a93243454ecd8f08e9ce9bd728a68bd3"

      def install
        bin.install "ned"
      end
    end
  end

  test do
    system "#{bin}/ned --version"
  end
end
