# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ned < Formula
  desc "Open any remote file in your local editor over SSH or Docker"
  homepage "https://github.com/ValeryCherneykin/ned"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_amd64.tar.gz"
      sha256 "d12ce85214bd0d7f0766e00c62f688ec1d24bc28e20e8e0410186546811497e7"

      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_darwin_arm64.tar.gz"
      sha256 "30dac0590f78303330f9cd40c370883bbb008354edc3b3587e07a050b9dfe782"

      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_amd64.tar.gz"
      sha256 "42faffa76c042d61972817a97919bb7891235c46fcbb978bb6773955e65a1994"
      define_method(:install) do
        bin.install "ned"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ValeryCherneykin/ned/releases/download/v0.3.0/ned_0.3.0_linux_arm64.tar.gz"
      sha256 "0cbf12f93a9a0e4ee75868bcf2e1b9a2842fae8b130f882b854e4b4df7a59df8"
      define_method(:install) do
        bin.install "ned"
      end
    end
  end

  test do
    system "#{bin}/ned --version"
  end
end
